'use strict'
export const spinner = '#spinner'
export const pageContainer = '#pageContainer'
export const visiblePage = '#app'
export const lead = '#leadId'
export const alert = '.top-right .toastr'
export const image = 'img'
export const logo = '#headerLogo'
