export const spinnerS = '.loader.loader_shutter.loader_detached.loader_fixed'
export const pageContainerS = '#pageContainer'
export const visiblePageS = '#app'
export const leadS = '#leadId'
export const alertS = '.redux-toastr .top-right'
export const imageS = 'img'
export const logoS = '#headerLogo'
